// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedback.proto

/*
Package feedback is a generated protocol buffer package.

It is generated from these files:
	feedback.proto

It has these top-level messages:
	PassengerFeedback
	CreateFeedbackRequest
	PassengerRequest
	FeedbackRequest
	BookingRequest
	FeedbackResponse
	PassengerResponse
*/
package feedback

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassengerFeedback struct {
	ID          string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	PassengerID string `protobuf:"bytes,2,opt,name=passengerID" json:"passengerID,omitempty"`
	BookingCode string `protobuf:"bytes,3,opt,name=bookingCode" json:"bookingCode,omitempty"`
	Feedback    string `protobuf:"bytes,4,opt,name=feedback" json:"feedback,omitempty"`
}

func (m *PassengerFeedback) Reset()                    { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string            { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()               {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PassengerFeedback) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type CreateFeedbackRequest struct {
	PassengerID string `protobuf:"bytes,2,opt,name=passengerID" json:"passengerID,omitempty"`
	BookingCode string `protobuf:"bytes,3,opt,name=bookingCode" json:"bookingCode,omitempty"`
	Feedback    string `protobuf:"bytes,4,opt,name=feedback" json:"feedback,omitempty"`
}

func (m *CreateFeedbackRequest) Reset()                    { *m = CreateFeedbackRequest{} }
func (m *CreateFeedbackRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeedbackRequest) ProtoMessage()               {}
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateFeedbackRequest) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *CreateFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *CreateFeedbackRequest) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type PassengerRequest struct {
	PassengerID string `protobuf:"bytes,1,opt,name=passengerID" json:"passengerID,omitempty"`
}

func (m *PassengerRequest) Reset()                    { *m = PassengerRequest{} }
func (m *PassengerRequest) String() string            { return proto.CompactTextString(m) }
func (*PassengerRequest) ProtoMessage()               {}
func (*PassengerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PassengerRequest) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

type FeedbackRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *FeedbackRequest) Reset()                    { *m = FeedbackRequest{} }
func (m *FeedbackRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedbackRequest) ProtoMessage()               {}
func (*FeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FeedbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type BookingRequest struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *BookingRequest) Reset()                    { *m = BookingRequest{} }
func (m *BookingRequest) String() string            { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()               {}
func (*BookingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BookingRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type FeedbackResponse struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *FeedbackResponse) Reset()                    { *m = FeedbackResponse{} }
func (m *FeedbackResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedbackResponse) ProtoMessage()               {}
func (*FeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FeedbackResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type PassengerResponse struct {
	PassengerID string               `protobuf:"bytes,1,opt,name=passengerID" json:"passengerID,omitempty"`
	Feedbacks   []*PassengerFeedback `protobuf:"bytes,2,rep,name=feedbacks" json:"feedbacks,omitempty"`
}

func (m *PassengerResponse) Reset()                    { *m = PassengerResponse{} }
func (m *PassengerResponse) String() string            { return proto.CompactTextString(m) }
func (*PassengerResponse) ProtoMessage()               {}
func (*PassengerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PassengerResponse) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *PassengerResponse) GetFeedbacks() []*PassengerFeedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

func init() {
	proto.RegisterType((*PassengerFeedback)(nil), "PassengerFeedback")
	proto.RegisterType((*CreateFeedbackRequest)(nil), "CreateFeedbackRequest")
	proto.RegisterType((*PassengerRequest)(nil), "PassengerRequest")
	proto.RegisterType((*FeedbackRequest)(nil), "FeedbackRequest")
	proto.RegisterType((*BookingRequest)(nil), "BookingRequest")
	proto.RegisterType((*FeedbackResponse)(nil), "FeedbackResponse")
	proto.RegisterType((*PassengerResponse)(nil), "PassengerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeedbackService service

type FeedbackServiceClient interface {
	Add(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	GetByPassengerId(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*PassengerResponse, error)
	GetByBookingCode(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*PassengerFeedback, error)
	Delete(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) Add(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := grpc.Invoke(ctx, "/FeedbackService/add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetByPassengerId(ctx context.Context, in *PassengerRequest, opts ...grpc.CallOption) (*PassengerResponse, error) {
	out := new(PassengerResponse)
	err := grpc.Invoke(ctx, "/FeedbackService/getByPassengerId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetByBookingCode(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*PassengerFeedback, error) {
	out := new(PassengerFeedback)
	err := grpc.Invoke(ctx, "/FeedbackService/getByBookingCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) Delete(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := grpc.Invoke(ctx, "/FeedbackService/delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedbackService service

type FeedbackServiceServer interface {
	Add(context.Context, *CreateFeedbackRequest) (*FeedbackResponse, error)
	GetByPassengerId(context.Context, *PassengerRequest) (*PassengerResponse, error)
	GetByBookingCode(context.Context, *BookingRequest) (*PassengerFeedback, error)
	Delete(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).Add(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetByPassengerId(ctx, req.(*PassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).Delete(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _FeedbackService_Add_Handler,
		},
		{
			MethodName: "getByPassengerId",
			Handler:    _FeedbackService_GetByPassengerId_Handler,
		},
		{
			MethodName: "getByBookingCode",
			Handler:    _FeedbackService_GetByBookingCode_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _FeedbackService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedback.proto",
}

func init() { proto.RegisterFile("feedback.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4f, 0x4f, 0xbb, 0x40,
	0x10, 0x2d, 0xb4, 0x69, 0x7e, 0x9d, 0x26, 0x2d, 0x9d, 0xe4, 0x67, 0x08, 0xa7, 0xba, 0xf1, 0xd0,
	0xd3, 0x6a, 0xd0, 0x8b, 0xf1, 0x46, 0x89, 0x09, 0x37, 0x83, 0x9f, 0x00, 0xd8, 0x91, 0x90, 0x1a,
	0x16, 0x59, 0xd4, 0x78, 0xf6, 0xfb, 0xfa, 0x19, 0x4c, 0xa1, 0xfc, 0x11, 0x6a, 0xf4, 0xe2, 0x6d,
	0x77, 0xe6, 0xed, 0xbc, 0xf7, 0xe6, 0x65, 0x61, 0xf1, 0x40, 0x24, 0xc2, 0x20, 0xda, 0xf1, 0x2c,
	0x97, 0x85, 0x64, 0xef, 0x1a, 0xac, 0xee, 0x02, 0xa5, 0x28, 0x8d, 0x29, 0xbf, 0x3d, 0xf4, 0x70,
	0x01, 0xba, 0xe7, 0x9a, 0xda, 0x5a, 0xdb, 0xcc, 0x7c, 0x3d, 0x71, 0x71, 0x0d, 0xf3, 0xac, 0x06,
	0x79, 0xae, 0xa9, 0x97, 0x8d, 0x6e, 0x69, 0x8f, 0x08, 0xa5, 0xdc, 0x25, 0x69, 0xbc, 0x95, 0x82,
	0xcc, 0x71, 0x85, 0xe8, 0x94, 0xd0, 0x82, 0x7f, 0x35, 0xb7, 0x39, 0x29, 0xdb, 0xcd, 0x9d, 0xbd,
	0xc2, 0xff, 0x6d, 0x4e, 0x41, 0x41, 0xb5, 0x02, 0x9f, 0x9e, 0x9e, 0x49, 0x15, 0x7f, 0x4e, 0x7c,
	0x05, 0x46, 0xe3, 0xfe, 0x1b, 0x4e, 0x6d, 0xc0, 0xc9, 0x4e, 0x61, 0xd9, 0x17, 0xda, 0xdb, 0x18,
	0x3b, 0x83, 0x85, 0x53, 0x69, 0xa8, 0x11, 0x08, 0x93, 0x68, 0xaf, 0xb0, 0xc2, 0x94, 0x67, 0xc6,
	0xc0, 0x68, 0x07, 0xa9, 0x4c, 0xa6, 0x8a, 0x06, 0x93, 0xe2, 0x4e, 0x40, 0x0d, 0xe8, 0x47, 0x8d,
	0x78, 0x01, 0xb3, 0xda, 0xa5, 0x32, 0xf5, 0xf5, 0x78, 0x33, 0xb7, 0x91, 0x0f, 0x92, 0xf6, 0x5b,
	0x90, 0xfd, 0xa1, 0xb5, 0xb6, 0xee, 0x29, 0x7f, 0x49, 0x22, 0x42, 0x1b, 0xc6, 0x81, 0x10, 0x78,
	0xc2, 0x8f, 0xc6, 0x63, 0xad, 0x78, 0x5f, 0x3e, 0x1b, 0xe1, 0x0d, 0x18, 0x31, 0x15, 0xce, 0x5b,
	0x43, 0xe6, 0x09, 0x5c, 0xf1, 0xfe, 0x9a, 0x2d, 0xe4, 0x03, 0x5b, 0x6c, 0x84, 0xd7, 0x87, 0xc7,
	0x4e, 0x27, 0xc0, 0x25, 0xff, 0xba, 0x4a, 0xeb, 0x88, 0x11, 0x36, 0xc2, 0x73, 0x98, 0x0a, 0x7a,
	0xa4, 0x82, 0xd0, 0xe0, 0xbf, 0x11, 0x1a, 0x4e, 0xcb, 0x2f, 0x70, 0xf9, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xfc, 0xe7, 0x8b, 0x14, 0x03, 0x00, 0x00,
}
