// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedback.proto

/*
Package feedback is a generated protocol buffer package.

It is generated from these files:
	feedback.proto

It has these top-level messages:
	PassengerFeedback
	Passenger
	Booking
	CreateFeedbackRequest
	FeedbackRequest
	BookingRequest
	FeedbackResponse
*/
package feedback

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PassengerFeedback struct {
	ID          string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	PassengerID string `protobuf:"bytes,2,opt,name=passengerID" json:"passengerID,omitempty"`
	BookingCode string `protobuf:"bytes,3,opt,name=bookingCode" json:"bookingCode,omitempty"`
	Feedback    string `protobuf:"bytes,4,opt,name=feedback" json:"feedback,omitempty"`
}

func (m *PassengerFeedback) Reset()                    { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string            { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()               {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PassengerFeedback) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type Passenger struct {
	ID       string               `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Feedback []*PassengerFeedback `protobuf:"bytes,2,rep,name=feedback" json:"feedback,omitempty"`
}

func (m *Passenger) Reset()                    { *m = Passenger{} }
func (m *Passenger) String() string            { return proto.CompactTextString(m) }
func (*Passenger) ProtoMessage()               {}
func (*Passenger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Passenger) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Passenger) GetFeedback() []*PassengerFeedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type Booking struct {
	Code        string             `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	PassengerID string             `protobuf:"bytes,2,opt,name=passengerID" json:"passengerID,omitempty"`
	Feedback    *PassengerFeedback `protobuf:"bytes,3,opt,name=feedback" json:"feedback,omitempty"`
}

func (m *Booking) Reset()                    { *m = Booking{} }
func (m *Booking) String() string            { return proto.CompactTextString(m) }
func (*Booking) ProtoMessage()               {}
func (*Booking) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Booking) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Booking) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *Booking) GetFeedback() *PassengerFeedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type CreateFeedbackRequest struct {
	PassengerID string `protobuf:"bytes,2,opt,name=passengerID" json:"passengerID,omitempty"`
	BookingCode string `protobuf:"bytes,3,opt,name=bookingCode" json:"bookingCode,omitempty"`
	Feedback    string `protobuf:"bytes,4,opt,name=feedback" json:"feedback,omitempty"`
}

func (m *CreateFeedbackRequest) Reset()                    { *m = CreateFeedbackRequest{} }
func (m *CreateFeedbackRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeedbackRequest) ProtoMessage()               {}
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateFeedbackRequest) GetPassengerID() string {
	if m != nil {
		return m.PassengerID
	}
	return ""
}

func (m *CreateFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *CreateFeedbackRequest) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type FeedbackRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *FeedbackRequest) Reset()                    { *m = FeedbackRequest{} }
func (m *FeedbackRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedbackRequest) ProtoMessage()               {}
func (*FeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FeedbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type BookingRequest struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *BookingRequest) Reset()                    { *m = BookingRequest{} }
func (m *BookingRequest) String() string            { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()               {}
func (*BookingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BookingRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type FeedbackResponse struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *FeedbackResponse) Reset()                    { *m = FeedbackResponse{} }
func (m *FeedbackResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedbackResponse) ProtoMessage()               {}
func (*FeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FeedbackResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*PassengerFeedback)(nil), "PassengerFeedback")
	proto.RegisterType((*Passenger)(nil), "Passenger")
	proto.RegisterType((*Booking)(nil), "Booking")
	proto.RegisterType((*CreateFeedbackRequest)(nil), "CreateFeedbackRequest")
	proto.RegisterType((*FeedbackRequest)(nil), "FeedbackRequest")
	proto.RegisterType((*BookingRequest)(nil), "BookingRequest")
	proto.RegisterType((*FeedbackResponse)(nil), "FeedbackResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeedbackService service

type FeedbackServiceClient interface {
	Add(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	GetById(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*PassengerFeedback, error)
	GetByBookingCode(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*PassengerFeedback, error)
	Delete(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) Add(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := grpc.Invoke(ctx, "/FeedbackService/add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetById(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*PassengerFeedback, error) {
	out := new(PassengerFeedback)
	err := grpc.Invoke(ctx, "/FeedbackService/getById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetByBookingCode(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*PassengerFeedback, error) {
	out := new(PassengerFeedback)
	err := grpc.Invoke(ctx, "/FeedbackService/getByBookingCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) Delete(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := grpc.Invoke(ctx, "/FeedbackService/delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedbackService service

type FeedbackServiceServer interface {
	Add(context.Context, *CreateFeedbackRequest) (*FeedbackResponse, error)
	GetById(context.Context, *FeedbackRequest) (*PassengerFeedback, error)
	GetByBookingCode(context.Context, *BookingRequest) (*PassengerFeedback, error)
	Delete(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).Add(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetById(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).Delete(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _FeedbackService_Add_Handler,
		},
		{
			MethodName: "getById",
			Handler:    _FeedbackService_GetById_Handler,
		},
		{
			MethodName: "getByBookingCode",
			Handler:    _FeedbackService_GetByBookingCode_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _FeedbackService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedback.proto",
}

func init() { proto.RegisterFile("feedback.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4e, 0xb3, 0x40,
	0x14, 0xc5, 0x0b, 0x6d, 0xda, 0xaf, 0xb7, 0x09, 0xa5, 0x37, 0xf9, 0x0c, 0xe9, 0x0a, 0x27, 0x2e,
	0xba, 0x1a, 0x23, 0xae, 0xdc, 0x52, 0x62, 0x42, 0xdc, 0x18, 0x7d, 0x02, 0x60, 0xae, 0x84, 0xd4,
	0x30, 0x08, 0xa8, 0x71, 0xed, 0xab, 0xfa, 0x20, 0x06, 0x28, 0x74, 0xa4, 0x18, 0xdd, 0xb8, 0x83,
	0xfb, 0xe7, 0xfc, 0xee, 0x39, 0xc9, 0x80, 0xf1, 0x40, 0x24, 0xc2, 0x20, 0xda, 0xf1, 0x2c, 0x97,
	0xa5, 0x64, 0xef, 0x1a, 0xac, 0x6e, 0x83, 0xa2, 0xa0, 0x34, 0xa6, 0xfc, 0x7a, 0xdf, 0x43, 0x03,
	0x74, 0xdf, 0xb3, 0x34, 0x5b, 0xdb, 0xcc, 0xef, 0xf4, 0xc4, 0x43, 0x1b, 0x16, 0x59, 0x3b, 0xe4,
	0x7b, 0x96, 0x5e, 0x37, 0xd4, 0x52, 0x35, 0x11, 0x4a, 0xb9, 0x4b, 0xd2, 0x78, 0x2b, 0x05, 0x59,
	0xe3, 0x66, 0x42, 0x29, 0xe1, 0x1a, 0xfe, 0xb5, 0x6c, 0x6b, 0x52, 0xb7, 0xbb, 0x7f, 0x76, 0x03,
	0xf3, 0xee, 0x88, 0x23, 0x38, 0x57, 0x16, 0x75, 0x7b, 0xbc, 0x59, 0x38, 0xc8, 0x8f, 0x4e, 0x56,
	0xc4, 0x24, 0xcc, 0xdc, 0x86, 0x8b, 0x08, 0x93, 0xa8, 0x3a, 0xa7, 0x11, 0xab, 0xbf, 0x7f, 0xe1,
	0x45, 0x05, 0x56, 0x46, 0x7e, 0x02, 0xbe, 0xc2, 0xff, 0x6d, 0x4e, 0x41, 0x49, 0x5d, 0x8f, 0x9e,
	0x9e, 0xa9, 0x28, 0xff, 0x3c, 0xb6, 0x53, 0x58, 0xf6, 0x91, 0xbd, 0xf0, 0xd8, 0x19, 0x18, 0xfb,
	0x30, 0xda, 0x89, 0x81, 0x4c, 0x18, 0x03, 0xf3, 0x20, 0x54, 0x64, 0x32, 0x2d, 0xa8, 0xaf, 0xe4,
	0x7c, 0x68, 0x07, 0xda, 0x3d, 0xe5, 0x2f, 0x49, 0x44, 0xe8, 0xc0, 0x38, 0x10, 0x02, 0x4f, 0xf8,
	0xa0, 0xff, 0xf5, 0x8a, 0xf7, 0x55, 0xd9, 0x08, 0x2f, 0x60, 0x16, 0x53, 0xe9, 0xbe, 0xf9, 0x02,
	0x4d, 0xde, 0xdf, 0x18, 0x08, 0x9a, 0x8d, 0xf0, 0x0a, 0xcc, 0x7a, 0xc5, 0x55, 0x72, 0x59, 0xf2,
	0xaf, 0xbe, 0xbe, 0x59, 0x3d, 0x87, 0xa9, 0xa0, 0x47, 0x2a, 0x69, 0x00, 0x36, 0x74, 0x5e, 0x38,
	0xad, 0xdf, 0xc5, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x3e, 0x64, 0xb5, 0x29, 0x03,
	0x00, 0x00,
}
