// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"grabvn-golang-bootcamp/internal/bootcamp"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) bootcamp.Event {
	message := bootcamp.NewMessage(phrase)
	greeter := bootcamp.NewGreeter(message)
	event := bootcamp.NewEvent(greeter)
	return event
}
