db:
  host: localhost
  port: 5432
  user: postgres
  password: example
  dbname: postgres
server:
  port: 8080
rpc:
  port: 9000
  certFile: ./configs/cert.pem
  keyFile: ./configs/key.pem
  passphrase: example